DROP DATABASE IF EXISTS elsie;
CREATE DATABASE IF NOT EXISTS elsie;
USE elsie;

DROP TABLE IF EXISTS ContactUs;
CREATE TABLE ContactUs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UNIQUE KEY (email)
);
